### PR TITLE
readline for gnureadline, license info, tick build

### PR DESCRIPTION
**Pull request by pmlandwehr**

### CODE REVIEW

**Comment by deargle** [comment]
@pmlandwehr  what gives, why is it that psiturk can use `gnureadline` but you have to use `readline` in conda? Can you enlighten me?

And I just noticed that LICENSE was not found. I actually didn't include that file in the manifest for 2.1.6, I think... I'll go check.

EDIT: yeah it's not in 2.1.6. It's in master, though. So next tag will get it. Let me know if there's anything you need me to do sooner rather than later.

**Comment by pmlandwehr** [comment]
A bit of luck, really. Google show me [this](https://github.com/ContinuumIO/anaconda-issues/issues/152), which suggested the error could be caused by an older version of libreadline, and could be solved by including `readline` directly (or, alternately, by linking `ncurses`). conda-forge has feedstocks for both [`gnureadline`](https://github.com/conda-forge/gnureadline-feedstock) and [`readline`](https://github.com/conda-forge/readline-feedstock), but both are equally up-to-date. The latter feedstock, however, explicity links `ncurses` into the build while the former does not. (cc @jakirkham and @ocefpaf since the `gnureadline` feedstock might want a patch.)

**Comment by jakirkham** [comment]
cc @ocefpaf

**Comment by jakirkham** [comment]
IIRC `gnureadline` bundles its own copy of `readline` internally. I don't know how they build it, but would assume it is not linked to `ncurses`.

Sorry it's been awhile since I've touched `gnureadline`. I started building `readline` a long time back because it just avoided many problems and haven't looked back.

So does `psiturk` require `gnureadline` or is it an optional dependency? If the latter, maybe you could just drop it.

Are there any issues with `ncurses` or `readline` that I need to be aware of here?

**Comment by pmlandwehr** [comment]
Closing and re-forking since there are conflicts with travis.

**Pull request closed without merging**
